debug: true
spring:
  datasource:
    url: jdbc:h2:mem:mybatis
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
  thymeleaf:
    cache: false # 取消thymeleaf模板引擎的缓存功能
  h2:
    console:
      enabled: true
mybatis:
  configuration:
    use-generated-keys: true