CREATE SCHEMA IF NOT EXISTS MYBATIS;

SET SCHEMA MYBATIS;

CREATE TABLE SYS_ROLE (
  ID          BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  ROLE_NAME   VARCHAR(50) COMMENT '角色名',
  ENABLED     INT COMMENT '有效标志',
  CREATE_BY   BIGINT COMMENT '创建人',
  CREATE_TIME DATETIME COMMENT '创建时间',
  PRIMARY KEY (ID)
);